### ISSUE TITLE
Add 'beep' as dependency on wiki

### ISSUE THREAD

**Issue by xDShot** [4815162342lost/steam_gifts_bot#1]
Not all distros have this pre-installed, so I was getting error:

> Traceback (most recent call last):
>   File "sg.py", line 360, in <module>
>     do_beep("coockie_exept")
>   File "sg.py", line 313, in do_beep
>     call(["beep", "-l 2000",  "-f 1900", "-r 3"])
>   File "/usr/lib/python3.5/subprocess.py", line 557, in call
>     with Popen(_popenargs, *_kwargs) as p:
>   File "/usr/lib/python3.5/subprocess.py", line 947, in **init**
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> FileNotFoundError: [Errno 2] No such file or directory: 'beep'

until I noticed that I don't have this binary at all.

**Comment by 4815162342lost** [comment]
Try to unstall beep

On debian-based distro:
`sudo apt install beep`

**Comment by 4815162342lost** [comment]
Done.

**Comment by xDShot** [comment]
Thanks :)
