### ISSUE TITLE
Бот не вступает в раздачи - Unknown error: 'NoneType' object has no attribute 'form'

### ISSUE THREAD

**Issue by Yrok472** [4815162342lost/steam_gifts_bot#12]
При попытке вступить в какую либо раздачу выдается следующее сообщение, пример:

`Working with link: https://www.steamgifts.com/giveaway/0T3Xd/ftl-faster-than-light`
`Unknown error: 'NoneType' object has no attribute 'form'`

До этого более двух лет работало без нареканий. Авторизация работает, проблема происходит в момент попытки вступления в раздачу.

Окружение:

Python 3.6.9
Ubuntu 18.04.4 LTS

**Comment by 4815162342lost** [comment]
Привет,

Спасибо за репорт. 

https://github.com/4815162342lost/steam_gifts_bot/commit/fef2bbcda1f1efc1b61ffb9806589505bb589fcf -- вступление в раздачу исправлено. Идёт тестирование в данный момент.

**Comment by 4815162342lost** [comment]
https://github.com/4815162342lost/steam_gifts_bot/blob/master/sg.py -- прошу заменить sg.py и переоткрыть тему, если появятся какие-то проблемы или вопросы.

Хорошей недели!

**Comment by Yrok472** [comment]
Фикс работает :) Тебе спасибо!

**Comment by YogSottot** [comment]
В директории create_docker_image осталась старая версия файла.

**Comment by 4815162342lost** [comment]
> В директории create_docker_image осталась старая версия файла.

Исправил, спасибо. Надо будет переделать docker-file и добавить копирование из основной репы. Попробую заняться позже.
