### ISSUE TITLE
Unable to install the newer version?

### ISSUE THREAD

**Issue by throawaygit** [4815162342lost/steam_gifts_bot#19]
Installing the script using ```
 wget -O /tmp/sg.deb https://github.com/4815162342lost/steam_gifts_bot/raw/master/create_deb_package_sources/steamgiftsbot.deb
sudo apt install /tmp/sg.deb```  install the previous version, overwriting sg.py, located in `/opt/steam_gifts/sg.py` with the newer one causes the service to prompt an error 

```
systemd[2114]: steam_gifts.service: Failed at step EXEC spawning /opt/steam_gifts/sg.py: Exec format error
systemd[1]: steam_gifts.service: Main process exited, code=exited, status=203/EXEC
systemd[1]: steam_gifts.service: Failed with result 'exit-code'.`
```

**Comment by 4815162342lost** [comment]
Hello. I did not update deb-package a long time.

But few seconds ago i updated the deb-package. Please, update once again:
```
wget -O /tmp/sg.deb https://github.com/4815162342lost/steam_gifts_bot/raw/master/create_deb_package_sources/steamgiftsbot.deb 
sudo apt install /tmp/sg.deb
```

And script should work.

If not:
Please, check perm of /opt/steam_gifts/sg.py file (ls -l /opt/steam_gifts/sg.py). Should be -rwxr-xr-x
If not, do
```
chmod 755 /opt/steam_gifts/sg.py
systemctl restart steam_gifts.service
```

**Comment by throawaygit** [comment]
Thanks for a quick response and update, much love
