### ISSUE TITLE
"pip3 install time" fails

### ISSUE THREAD

**Issue by grray** [4815162342lost/steam_gifts_bot#2]
```
# pip3 install time requests random bs4 os json platform re sys subprocess datetime notify2 gi
Collecting time
  Could not find a version that satisfies the requirement time (from versions: )
No matching distribution found for time
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

OS is Ubuntu 16.04.1, hardware: raspberry pi 2 (arm processor).
All is working this way

```
pip3 install requests bs4 datetime notify2 gi
```

I guess other packages kind of built-in, so they can be removed from "requirements" help section.

**Comment by 4815162342lost** [comment]
Dear grray,

I fixed wiki. Could you, please, check and close issues, if all OK now?

Thanks in advance!

**Comment by grray** [comment]
It should be opposite:
Some modules are a standard python 3 modules and not needed to install (for example time, random, os, json, platform, re, sys, subprocess).

**Comment by 4815162342lost** [comment]
Done.

**Comment by grray** [comment]
Now it's good. Thanks!
