### ISSUE TITLE
Next page endless loop

### ISSUE THREAD

**Issue by TheGoblinHero** [4815162342lost/steam_gifts_bot#20]
Today I've found an endless loop. There's a "Deals" section at the bottom and one of the deals has name "Next fest badge [100xp]".
do_requests function thinks that there's a next page and loops forever.
My fix is to change next page detection line so it won't trigger on deals, game names, etc:
`if r.text.find("<span>Next</span>") == -1 or type(page_number) != int:`

**Comment by 4815162342lost** [comment]
Hello. Thanks for your report.

Bug was fixed on Dec 30, 2023 via different way:
https://github.com/4815162342lost/steam_gifts_bot/commit/2a3f15b8fc4a671279be171b92b5825a5e19f924#diff-2786868fdc585427b26696bc4990170e24c6585f817c88df5834b9ffff3685a9
