### ISSUE TITLE
I think it doesn't work anymore

### ISSUE THREAD

**Issue by EEnigma-Hub** [4815162342lost/steam_gifts_bot#22]
For the last two months, I have been running the code on my vds server non-stop, but I have not won any sweepstakes. Before, I was earning at least 2-3 games a month. Most likely, the steamgifts.com website may have found a solution against bots.

**Comment by 4815162342lost** [comment]
Last time i won 2 weeks ago. In last mouth i won 5 games. hope that bot works fine. Please, check logs.

**Comment by 4815162342lost** [comment]
Script still works. I won today.

**Comment by 4815162342lost** [comment]
I won one more game today. Still works.
