### ISSUE TITLE
Ру-версия

### ISSUE THREAD

**Issue by Votar9** [4815162342lost/steam_gifts_bot#9]
Привет. Спасибо за топовый скрипт - пользуюсь им уже несколько месяцев. 
Делаю для себя перевод сообщений в консоли, мне так удобнее, да и глазам приятнее на кириллицу смотреть. Прикреплю сюда свой SGB 1.4.4 с переводом, МБ выложишь как ру-версию)
PS: вообще ничего не перекодировал, поэтому отдельные элементы инглиша остались. Единственное подкрутил тайминги в сторону уменьшения, на мой взгляд они сильно завышены.
https://yadi.sk/d/hjTFrOeW7SF56Q

**Comment by 4815162342lost** [comment]
Привет.

Спасибо за перевод! Отдельно выкладывать не буду, надо постараться как-нибудь создать одну версию, чтобы через конфигурауионные файлы переклчать язык.

Надо подумать над тем, как это сделать.

**Comment by 4815162342lost** [comment]
К сожалению, у меня нет свободного времени, чтобы потартить на перевод. И не уверен, что это будет востаребованный функционал. Но если вы хотите, можете сделать перевод и отправить коммит. Я обязательно егт приму.
